import {
  createContext,
  ReactNode,
  useCallback,
  useContext,
  useMemo,
} from 'react';
import { useLocalStorage } from './hooks/useLocalStorage';

type Language = 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined,
);

export const translations: Record<Language, Record<string, string>> = {
  en: {
    'Add Template': 'Add Template',
    Template: 'Template',
    'FFmpeg Tool': 'FFmpeg Tool',
    'Command Template': 'Command Template',
    'Select a template': 'Select a template',
    ffmpegStalledTitle: 'FFmpeg appears unresponsive',
    ffmpegStalledDescription:
      'No output received for a while. The process may be stuck. Continue waiting?',
    'Continue Waiting': 'Continue Waiting',
    'FFmpeg Command': 'FFmpeg Command',
    'Enter FFmpeg command or drag & drop files here':
      'Enter FFmpeg command or drag & drop files here',
    Terminal: 'Terminal',
    Start: 'Start',
    Stop: 'Stop',
    'Stopping...': 'Stopping...',
    Activity: 'Activity',
    Shell: 'Shell',
    Workspace: 'Workspace',
    Ready: 'Ready',
    Running: 'Running',
    'Needs Setup': 'Needs Setup',
    'Pick a template, input, and output to get started.':
      'Pick a template, input, and output to get started.',
    'Review the generated command and start when ready.':
      'Review the generated command and start when ready.',
    'Processing is in progress. You can watch live output below.':
      'Processing is in progress. You can watch live output below.',
    'Stopping the current process…': 'Stopping the current process…',
    'Open Shell': 'Open Shell',
    'Show Activity': 'Show Activity',
    'Working from template': 'Working from template',
    'Custom command': 'Custom command',
    'No template selected': 'No template selected',
    'Step 1': 'Step 1',
    'Step 2': 'Step 2',
    'Step 3': 'Step 3',
    'Choose template': 'Choose template',
    'Pick input': 'Pick input',
    'Pick output': 'Pick output',
    'Activity stays here while the converter stays above.':
      'Activity stays here while the converter stays above.',
    'Open a shell for quick checks without leaving the converter.':
      'Open a shell for quick checks without leaving the converter.',
    Progress: 'Progress',
    Logs: 'Logs',
    Clear: 'Clear',
    Copy: 'Copy',
    'Console Output': 'Console Output',
    'Copy raw text': 'Copy raw text',
    'Clear console': 'Clear console',
    'Ready to process...': 'Ready to process...',
    Paused: 'Paused',
    'Processing...': 'Processing...',
    'Waiting for progress...': 'Waiting for progress...',
    'Installing FFmpeg': 'Installing FFmpeg',
    Downloading: 'Downloading',
    Extracting: 'Extracting',
    'Loading FFmpeg assets...': 'Loading FFmpeg assets...',
    Error: 'Error',
    'Try Again': 'Try Again',
    'Download FFmpeg': 'Download FFmpeg',
    'FFmpeg is not detected on your system. Please download it to continue.':
      'FFmpeg is not detected on your system. Please download it to continue.',
    'Select a version:': 'Select a version:',
    'The latest version of FFmpeg will be downloaded automatically.':
      'The latest version of FFmpeg will be downloaded automatically.',
    'Download and Install FFmpeg': 'Download and Install FFmpeg',
    'Check for updates': 'Check for updates',
    'Update FFmpeg': 'Update FFmpeg',
    Update: 'Update',
    'Updating FFmpeg': 'Updating FFmpeg',
    'FFmpeg updated successfully.': 'FFmpeg updated successfully.',
    'Update failed': 'Update failed',
    'FFmpeg is up to date.': 'FFmpeg is up to date.',
    'Failed to check for updates.': 'Failed to check for updates.',
    'Latest version': 'Latest version',
    'Current version': 'Current version',
    'Stop the current task before updating.':
      'Stop the current task before updating.',
    'Failed to fetch FFmpeg assets.': 'Failed to fetch FFmpeg assets.',
    'Edit Template': 'Edit Template',
    'Add New Template': 'Add New Template',
    'Name (English)': 'Name (English)',
    'Name (Chinese)': 'Name (Chinese)',
    Command: 'Command',
    'Description (English)': 'Description (English)',
    'Description (Chinese)': 'Description (Chinese)',
    Cancel: 'Cancel',
    Save: 'Save',
    'Select Input File': 'Select Input File',
    'Input File': 'Input File',
    'Select Output Folder': 'Select Output Folder',
    'Output Folder': 'Output Folder',
    'Output Name': 'Output Name',
    'Final Output Path': 'Final Output Path',
    'Media Details': 'Media Details',
    'Reading media details...': 'Reading media details...',
    'Failed to read media details.': 'Failed to read media details.',
    'Search by name, description, or command':
      'Search by name, description, or command',
    'All Templates': 'All Templates',
    'Built-in Templates': 'Built-in Templates',
    'Custom Templates': 'Custom Templates',
    All: 'All',
    'Built-in': 'Built-in',
    Custom: 'Custom',
    'All Devices': 'All Devices',
    'This Device': 'This Device',
    'No matching templates': 'No matching templates',
    Windows: 'Windows',
    macOS: 'macOS',
    Linux: 'Linux',
    'Windows / Linux': 'Windows / Linux',
    'Latest Result': 'Latest Result',
    'Command executed successfully.': 'Command executed successfully.',
    'Task complete. Your output is ready.':
      'Task complete. Your output is ready.',
    'Completed Output': 'Completed Output',
    'Open File': 'Open File',
    'Open Folder': 'Open Folder',
    'Run Again': 'Run Again',
    'Failed to open output file.': 'Failed to open output file.',
    'Failed to open output folder.': 'Failed to open output folder.',
    Duration: 'Duration',
    Resolution: 'Resolution',
    Video: 'Video',
    Audio: 'Audio',
    Subtitles: 'Subtitles',
    Format: 'Format',
    Size: 'Size',
    Bitrate: 'Bitrate',
    'Frame Rate': 'Frame Rate',
    Channels: 'Channels',
    'Sample Rate': 'Sample Rate',
    Tracks: 'Tracks',
    'No media details yet': 'No media details yet',
    'Select a first input file to inspect it here.':
      'Select a first input file to inspect it here.',
    'Selecting a template will replace the current command. Continue?':
      'Selecting a template will replace the current command. Continue?',
    'Delete this custom template?': 'Delete this custom template?',
    'This command has multiple input files; only the first -i is auto-bound from the input selector.':
      'This command has multiple input files; only the first -i is auto-bound from the input selector.',
    'Command copied to clipboard.': 'Command copied to clipboard.',
    'Log copied to clipboard.': 'Log copied to clipboard.',
    'Nothing to copy.': 'Nothing to copy.',
    'Failed to copy command.': 'Failed to copy command.',
    'Failed to copy logs.': 'Failed to copy logs.',
    'Failed to open terminal.': 'Failed to open terminal.',
    'Failed to select input file. Please try again.':
      'Failed to select input file. Please try again.',
    'Failed to select output folder. Please try again.':
      'Failed to select output folder. Please try again.',
    'Failed to save template. Please check your data.':
      'Failed to save template. Please check your data.',
    'Failed to delete template.': 'Failed to delete template.',
    'Failed to load templates.': 'Failed to load templates.',
    'Failed to check FFmpeg status.': 'Failed to check FFmpeg status.',
    'Please provide at least one name and description, and a command.':
      'Please provide at least one name and description, and a command.',
    'Drag & drop files or type manually': 'Drag & drop files or type manually',
    characters: 'characters',
    'Loading…': 'Loading…',
    'No templates available': 'No templates available',
    'Modify existing template': 'Modify existing template',
    'Create a new custom template': 'Create a new custom template',
    'Select a template or enter a command to begin':
      'Select a template or enter a command to begin',
    'Video & Audio Processing': 'Video & Audio Processing',
    Collapse: 'Collapse',
    Default: 'Default',
    Expand: 'Expand',
    'Running...': 'Running...',
    'Drop file here': 'Drop file here',
    'Toggle drawer': 'Toggle drawer',
    'Modified (from template)': 'Modified',
    'Reset to template': 'Reset to template',
    'From template': 'From template',
    Pipeline: 'Pipeline',
    'Estimated remaining': 'Estimated remaining',
    Input: 'Input',
    Output: 'Output',
    'No input': 'No input',
    'No command': 'No command',
    'No output': 'No output',
    Dismiss: 'Dismiss',
    "Don't show again": "Don't show again",
    Failed: 'Failed',
    'Task Failed': 'Task Failed',
    'Task failed. Check the activity log for details.':
      'Task failed. Check the activity log for details.',
    'View Logs': 'View Logs',
    'Enter a command or select a template.':
      'Enter a command or select a template.',
    'Select an input file to continue.': 'Select an input file to continue.',
    'Select an output folder to continue.':
      'Select an output folder to continue.',
    'Enter an output file name to continue.':
      'Enter an output file name to continue.',
    'Missing command': 'Missing command',
    'Missing input': 'Missing input',
    'Missing output': 'Missing output',
    'Press shortcut to start': 'Press shortcut to start',
    'to start': 'to start',
    Confirm: 'Confirm',
  },
  zh: {
    'Add Template': '添加模板',
    Template: '模板',
    'FFmpeg Tool': 'FFmpeg 工具',
    Terminal: '终端',
    'Command Template': '命令模板',
    'Select a template': '选择模板',
    ffmpegStalledTitle: 'FFmpeg 可能无响应',
    ffmpegStalledDescription:
      '已有一段时间没有收到输出，进程可能卡住了。是否继续等待？',
    'Continue Waiting': '继续等待',
    'FFmpeg Command': 'FFmpeg 命令',
    'Enter FFmpeg command or drag & drop files here':
      '输入 FFmpeg 命令或拖放文件到这里',
    Start: '开始',
    Stop: '停止',
    'Stopping...': '停止中...',
    Activity: '运行日志',
    Shell: '终端',
    Workspace: '工作台',
    Ready: '就绪',
    Running: '进行中',
    'Needs Setup': '待设置',
    'Pick a template, input, and output to get started.':
      '先选择模板、输入文件和输出位置。',
    'Review the generated command and start when ready.':
      '检查生成的命令，确认后即可开始。',
    'Processing is in progress. You can watch live output below.':
      '处理中，可在下方查看实时输出。',
    'Stopping the current process…': '正在停止当前任务…',
    'Open Shell': '打开终端',
    'Show Activity': '查看日志',
    'Working from template': '使用模板',
    'Custom command': '自定义命令',
    'No template selected': '未选择模板',
    'Step 1': '步骤 1',
    'Step 2': '步骤 2',
    'Step 3': '步骤 3',
    'Choose template': '选择模板',
    'Pick input': '选择输入',
    'Pick output': '选择输出',
    'Activity stays here while the converter stays above.':
      '转换流程始终保留在上方，运行信息集中在这里。',
    'Open a shell for quick checks without leaving the converter.':
      '无需离开当前页面，也可以打开终端做快速检查。',
    Progress: '进度',
    Logs: '日志',
    Clear: '清除',
    Copy: '复制',
    'Console Output': '控制台输出',
    'Copy raw text': '复制原始文本',
    'Clear console': '清空控制台',
    'Ready to process...': '准备就绪，等待处理...',
    'Select a template or enter a command to begin': '选择模板或输入命令以开始',
    Paused: '已暂停自动滚动',
    'Processing...': '处理中...',
    'Waiting for progress...': '等待进度...',
    'Installing FFmpeg': '正在安装 FFmpeg',
    Downloading: '下载中',
    Extracting: '解压中',
    'Loading FFmpeg assets...': '正在加载 FFmpeg 资源...',
    Error: '错误',
    'Try Again': '重试',
    'Download FFmpeg': '下载 FFmpeg',
    'FFmpeg is not detected on your system. Please download it to continue.':
      '系统未检测到 FFmpeg，请先下载后继续。',
    'Select a version:': '选择一个版本：',
    'The latest version of FFmpeg will be downloaded automatically.':
      '将自动下载最新版本的 FFmpeg。',
    'Download and Install FFmpeg': '下载并安装 FFmpeg',
    'Check for updates': '检查更新',
    'Update FFmpeg': '更新 FFmpeg',
    Update: '更新',
    'Updating FFmpeg': '正在更新 FFmpeg',
    'FFmpeg updated successfully.': 'FFmpeg 更新成功。',
    'Update failed': '更新失败',
    'FFmpeg is up to date.': 'FFmpeg 已是最新版本。',
    'Failed to check for updates.': '检查更新失败。',
    'Latest version': '最新版本',
    'Current version': '当前版本',
    'Stop the current task before updating.': '请先停止当前任务再更新。',
    'Failed to fetch FFmpeg assets.': '获取 FFmpeg 资源失败。',
    'Edit Template': '编辑模板',
    'Add New Template': '添加新模板',
    'Name (English)': '名称（英文）',
    'Name (Chinese)': '名称（中文）',
    Command: '命令',
    'Description (English)': '描述（英文）',
    'Description (Chinese)': '描述（中文）',
    Cancel: '取消',
    Confirm: '确认',
    Save: '保存',
    'Select Input File': '选择输入文件',
    'Input File': '输入文件',
    'Select Output Folder': '选择输出文件夹',
    'Output Folder': '输出文件夹',
    'Output Name': '输出文件名',
    'Final Output Path': '最终输出路径',
    'Media Details': '媒体信息',
    'Reading media details...': '正在读取媒体信息...',
    'Failed to read media details.': '读取媒体信息失败。',
    'Search by name, description, or command': '按名称、说明或命令搜索',
    'All Templates': '全部模板',
    'Built-in Templates': '内置模板',
    'Custom Templates': '自定义模板',
    All: '全部',
    'Built-in': '内置',
    Custom: '自定义',
    'All Devices': '全部设备',
    'This Device': '当前设备',
    'No matching templates': '没有匹配的模板',
    Windows: 'Windows',
    macOS: 'macOS',
    Linux: 'Linux',
    'Windows / Linux': 'Windows / Linux',
    'Latest Result': '最近结果',
    'Command executed successfully.': '命令执行成功。',
    'Task complete. Your output is ready.': '任务已完成，输出文件已经准备好。',
    'Completed Output': '输出结果',
    'Open File': '打开文件',
    'Open Folder': '打开文件夹',
    'Run Again': '再运行一次',
    'Failed to open output file.': '打开输出文件失败。',
    'Failed to open output folder.': '打开输出文件夹失败。',
    Duration: '时长',
    Resolution: '分辨率',
    Video: '视频',
    Audio: '音频',
    Subtitles: '字幕',
    Format: '格式',
    Size: '大小',
    Bitrate: '码率',
    'Frame Rate': '帧率',
    Channels: '声道',
    'Sample Rate': '采样率',
    Tracks: '字幕轨',
    'No media details yet': '还没有媒体信息',
    'Select a first input file to inspect it here.':
      '选择第一个输入文件后，会在这里显示媒体信息。',
    'Selecting a template will replace the current command. Continue?':
      '选择模板将覆盖当前命令，是否继续？',
    'Delete this custom template?': '确认删除该自定义模板吗？',
    'This command has multiple input files; only the first -i is auto-bound from the input selector.':
      '当前命令包含多个输入文件；输入选择器只会自动绑定第一个 -i，其余请手动调整。',
    'Command copied to clipboard.': '命令已复制到剪贴板。',
    'Log copied to clipboard.': '日志已复制到剪贴板。',
    'Nothing to copy.': '没有可复制的内容。',
    'Failed to copy command.': '复制命令失败。',
    'Failed to copy logs.': '复制日志失败。',
    'Failed to open terminal.': '打开终端失败。',
    'Failed to select input file. Please try again.':
      '选择输入文件失败，请重试。',
    'Failed to select output folder. Please try again.':
      '选择输出文件夹失败，请重试。',
    'Failed to save template. Please check your data.':
      '保存模板失败，请检查输入内容。',
    'Failed to delete template.': '删除模板失败。',
    'Failed to load templates.': '加载模板失败。',
    'Failed to check FFmpeg status.': '检查 FFmpeg 状态失败。',
    'Please provide at least one name and description, and a command.':
      '请至少填写一侧名称和描述，并提供命令。',
    'Drag & drop files or type manually': '拖拽文件或手动输入',
    characters: '个字符',
    'Loading…': '加载中…',
    'No templates available': '暂无可用模板',
    'Modify existing template': '修改现有模板',
    'Create a new custom template': '创建新的自定义模板',
    'Video & Audio Processing': '视频 & 音频处理',
    Collapse: '收起',
    Default: '默认',
    Expand: '展开',
    'Running...': '运行中...',
    'Drop file here': '拖放文件到这里',
    'Toggle drawer': '切换抽屉',
    'Modified (from template)': '已修改',
    'Reset to template': '重置为模板',
    'From template': '来自模板',
    Pipeline: '管线',
    'Estimated remaining': '预计剩余',
    Input: '输入',
    Output: '输出',
    'No input': '未选输入',
    'No command': '无命令',
    'No output': '未选输出',
    Dismiss: '关闭',
    "Don't show again": '不再提示',
    Failed: '失败',
    'Task Failed': '任务失败',
    'Task failed. Check the activity log for details.':
      '任务失败，请查看运行日志了解详情。',
    'View Logs': '查看日志',
    'Enter a command or select a template.': '请输入命令或选择模板。',
    'Select an input file to continue.': '请选择输入文件。',
    'Select an output folder to continue.': '请选择输出文件夹。',
    'Enter an output file name to continue.': '请输入输出文件名。',
    'Missing command': '缺少命令',
    'Missing input': '缺少输入',
    'Missing output': '缺少输出',
    'Press shortcut to start': '快捷键启动',
    'to start': '开始',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  // 语言偏好持久化：裸字符串（历史格式），非 JSON
  const [language, setLanguage] = useLocalStorage<Language>('language', 'en', {
    serialize: String,
    deserialize: (raw) => (raw || 'en') as Language,
  });

  const t = useCallback(
    (key: string): string => {
      const value = translations[language][key];
      if (!value && process.env.NODE_ENV === 'development') {
        console.warn(`[i18n] Missing translation key: "${key}" (${language})`);
      }
      return value || key;
    },
    [language],
  );

  const contextValue = useMemo(
    () => ({ language, setLanguage, t }),
    [language, setLanguage, t],
  );

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
